### ISSUE TITLE
Please add comments in models/tourModel.js 

### ISSUE THREAD

**Issue by JAgrit20** [JAgrit20/NATOURS_Project#8]
Brief about the libraries used in the file

**Comment by shanmukhkalasamudram** [comment]
I'm interested to do this, Can you assign this to me

**Comment by JAgrit20** [comment]
Ok create the pull request after the changes

**Comment by shanmukhkalasamudram** [comment]
I completed the changes, Can you accept the request

**Comment by shanmukhkalasamudram** [comment]
Is it okay? or anychanges required .
